[[app]]
name = "Obsidian"
aliases = ["obs", "notes"]
target = "obsidian://"

[[app]]
name = "Google Chrome"
aliases = ["chrome", "browser", "google"]
target = "https://google.com"

[[app]]
name = "Discord"
aliases = ["dc"]
target = "discord://"

[[app]]
name = "Spotify"
aliases = ["music", "sp"]
target = "spotify://"

[[app]]
name = "VS Code"
aliases = ["code", "vscode"]
target = "vscode://"

[[app]]
name = "GitHub"
aliases = ["gh"]
target = "https://github.com"

[[app]]
name = "Windows Terminal"
aliases = ["terminal", "wt"]
target = "wt.exe"

[[app]]
name = "Notepad"
aliases = ["pad"]
target = "notepad.exe"

[[app]]
name = "Youtube"
aliases = ["yt"]
target = "https://youtube.com"

[[app]]
name = "Gemini"
aliases = ["gemini"]
target = "https://gemini.google.com/app"

[[app]]
name = "ChatGPT"
aliases = ["chatgpt"]
target = "https://chatgpt.com/"
